### ISSUE TITLE
SecureString shown in plain text when using Test-ARMDeploymentResource 

### ISSUE THREAD

**Issue by anceng** [Ba4bes/ARMHelper#19]
The values of parameters that are defined as a securestring in the ARM Template file are shown in plain text using the Test-ARMDeploymentResource.

It would be logical to mimic the behavior of ARM template output when using the Powershell New-AzResourceGroupDeployment cmdlet or similar tools used for ARM template deployment. The behavior with those tools is that text that is defined as a securestring is obfuscated (the output shows *********** instead of the actual value).

You would probably need to change the way Get-ARMResource.ps1 handles the output created by Test-Az(ureRm)ResourceGroupDeployment

**Comment by Ba4bes** [comment]
Good point,  a securestring should not be shown by default as it is not expected behaviour.

I will look into this next week.

**Comment by Ba4bes** [comment]
Alright. So the output that was given comes from the Debug Output of Test-AzResourceGroupDeployment. This means that it is not handled as a securestring through the process by design. 
I have changed the output though. If a parameter is defined as a secure string in the template, it is recreated as a secure string when Get-ArmResource is called. 
Final output would be something like this
```CMD
adminPassword   System.Security.SecureString
```
The only disclaimer is that the value could be visible as plaintext in the process of running the command, as this is by design for Test-AzResourceGroupDeployment

**Comment by Ba4bes** [comment]
This will be added to the next release

**Comment by anceng** [comment]
Will leave this here for future reference.

I still had the issue that admin passwords were shown in plain text while using the ARM helper template in a Azure DevOps pipeline with the following command:
```powershell
Test-ARMDeploymentResource -ResourceGroupName $ResourceGroupName -TemplateFile $TemplateFile -TemplateParameterFile $TemplateParameterFile -Mode Complete | Select-Object *`
```

I was able to make sure the passwords were not shown in the template output by using the following command instead:
```powershell
Test-ARMDeploymentResource -ResourceGroupName $ResourceGroupName -TemplateFile $TemplateFile -TemplateParameterFile $TemplateParameterFile -Mode Complete | Select-Object -Property * -ExcludeProperty AdminPassword, Password
```

Here is the content of the yaml pipeline used in Azure DevOps:
```yaml
trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'vs2017-win2016'

variables:
    resourceGroupName: ''
    azureSubscription: ''

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: $(azureSubscription)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: 'West Europe'
    csmFile: 'DeploymentFiles/azuredeploy.json'
    csmParametersFile: 'DeploymentFiles/azuredeploy.parameters.test.json'
    deploymentMode: 'Validation'
- task: AzurePowerShell@3
  displayName: 'Show ARMhelper test results'
  inputs:
    azureSubscription:  $(azureSubscription)
    ScriptType: InlineScript
    Inline: |
        Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
        Install-Module -Name ARMHelper -Force -Scope CurrentUser
        Import-Module -Name AzureRM
        Import-Module -Name ARMHelper

        Test-ARMDeploymentResource -ResourceGroupName $(resourceGroupName) -TemplateFile "$(Build.SourcesDirectory)\Deploymentfiles\azuredeploy.json" -TemplateParameterFile "$(Build.SourcesDirectory)\Deploymentfiles\azuredeploy.parameters.test.json" -Mode Complete | Select-Object -Property * -ExcludeProperty AdminPassword, Password

        $Deployments = Get-AzureRmResourceGroupDeployment -ResourceGroupName $(resourceGroupName)
        
        if ($Deployments.ProvisioningState -notcontains "Running") {
            Remove-AzureRMResourceGroup -ResourceGroupName $(resourceGroupName) -Force
        }
    FailOnStandardError: true
    azurePowerShellVersion: LatestVersion
```
